d={'a':'apple','b':'banana','c':'cathode',1:10}
print(d.pop('c'))
print(d)
print(d.popitem())
d['d']=100
print(d)
print(d.get('a'))
print(d.setdefault((1,),'I love it'))
print(d.update({'c':'cathode','e':'Elephant'}))
print(d)
a=d.fromkeys((1,2,3,4,56,7,8,9,0),'I love it')
print(a.items())
print(d.copy())
print(d.keys())
print(d.values())
print(d.items())
print(a.clear())
print(d.clear())
print(d)
print(a)
