"""String in built methods are
a.upper()
a.lower()
a.capitaliz()
a.swapcase()
sorted(a)
a.split()
a.title()
a.isalpha()
a.isalnum()
a.isdigit()
a.index()
a.find()
a.count()
a.rindex()
a.rfind()
a.startswith()
a.endswith()
f'{a} add with{b}'()
'{} add {}'.format(a,b)
a.strip()
a.lstrip()
a.rstrip()
"""
a="     Iam studying B.Tech (4th)final yaer in viswam engineering college     "
print(a)
print(a.upper())
print(a.lower())

print(a.swapcase())
print(a.split('a',10))
print(sorted(a,reverse=True))
print(a.title())
print(a.count('I'))

print(a.index('t',2,349))
print(a.find('y'))
print( a.isalpha())

print(a.isalnum())
print(a.isdigit())
print(a.capitalize())
print(sorted(a))
print(a.rfind('s'))
print(a.rindex('s'))
print(a.index('t',2,349))
print(a.find('y'))
print(a.startswith('Iam'))
print(a.endswith('college'))
b=10
c=15
print(f'{a} in room number {b}')
print('{0} in room number {1}'.format(10,20))
print(a.strip())
print(a.lstrip())
print(a.rstrip())

